apiVersion: apps/v1
kind: Deployment
metadata:
          name: mongodb
          namespace: k8s-demo
spec:
     selector:
          matchLabels:
               app: mongodb        
     template:
            metadata:
                  labels: 
                       app: mongodb           
            spec:
                containers:
                       - name: mongodb
                         image: mongo
                         ports:
                              - containerPort: 27017
                         env:
                          - name: MONGO_INITDB_ROOT_USERNAME
                            valueFrom:
                                secretKeyRef:
                                        name: my-secret-map
                                        key: DB_USER
                          - name: MONGO_INITDB_ROOT_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                        name: my-secret-map
                                        key: DB_PASS
                         volumeMounts:
                                - name: mongo-data-dir
                                  mountPath: /data/db
                volumes: 
                       - name: mongo-data-dir
                         persistentVolumeClaim: 
                                   claimName:  mongo-pvc

---
apiVersion: v1
kind: Service
metadata: 
      name: mongo-service
      namespace: k8s-demo
spec:
    clusterIP: None
    selector:
          app: mongodb
    ports:
        - port: 27017
          targetPort: 27017                        
                                 