apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-webapp
    namespace: k8s-demo
spec:
    replicas: 3
    selector:
      matchLabels:
        app: my-webapp
    template: 
      metadata:
        labels:
          app: my-webapp
      spec:
        containers:
        - name: my-webapp
          imagePullPolicy: Always
          image: sachinmicrodockerhub/docker-rest-api:latest
          ports:
          - containerPort: 4545
          env:
            - name: MONGO_HOST
              valueFrom:
                   configMapKeyRef:
                          name: my-config-map
                          key: MONGO_HOST
            - name: MONGO_USER
              valueFrom:
                   secretKeyRef:
                          name: my-secret-map
                          key: DB_USER
            - name: MONGO_PASSWORD
              valueFrom:
                   secretKeyRef:
                          name: my-secret-map
                          key: DB_PASS                          
--- 
apiVersion: v1
kind: Service
metadata:
    name: my-webapp-service
    namespace: k8s-demo
spec:
    selector:
      app: my-webapp
    type: NodePort  
    ports:
      - port: 45450
        targetPort: 4545
        nodePort: 30007
