version: '3'
services:
       mongo: 
          image: 'mongo:4.0.4'
          container_name: mongodb
          restart: always
          ports:
                       - '27017:27017'
          environment:
               - MONGO_INITDB_ROOT_USERNAME=mongoadmin
               - MONGO_INITDB_ROOT_PASSWORD=secret
               - MONGO_INITDB_DATABASE=testdb